[project]
name = "vm-runner"
version = "0.1.0"
description = "Async VM runner for Virby"
requires-python = ">=3.13"
authors = [{ name = "Quinn Edenfield", email = "quinn@qeden.dev" }]
dependencies = [
  "aiofiles>=24.1.0",
]

[project.scripts]
vm-runner = "vm_runner.cli:cli_main"

[dependency-groups]
lint = [
  "isort>=5.12.0",
  "mypy>=1.0.0",
  "ruff>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
only-packages = true

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
use_parentheses = true

[tool.mypy]
check_untyped_defs = true
mypy_path = ["src"]
packages = ["vm_runner"]
pretty = true
python_version = "3.13"
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.uv]
package = true
default-groups = ["lint"]
