[project]
name = "virby-vm-runner"
version = "0.2.0"
description = "Vfkit-based VM runner for Virby"
requires-python = ">=3.10"
authors = [{ name = "Quinn Edenfield", email = "quinn@qeden.dev" }]
dependencies = [
  "aiofiles>=24.1.0",
  "httpx>=0.28.1",
]

[project.scripts]
virby-vm = "virby_vm_runner.cli:cli_main"

[dependency-groups]
dev = [
  "basedpyright>=1.31.0",
  "commitizen>=4.8.3",
  "ipython>=8.37.0",
  "isort>=5.12.0",
  "mypy>=1.0.0",
  "ruff>=0.1.0",
  "types-aiofiles>=24.1.0.20250606",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.basedpyright]
include = ["src"]
exclude = [
  "**/node_modules",
  "**/__pycache__",
]
reportMissingImports = "none"
reportMissingTypeStubs = false
reportUnsupportedDunderAll = "none"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "vm-runner-v$version"
ignored_tag_formats = ["latest"]
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true

[tool.hatch.build.targets.wheel]
packages = ["src/virby_vm_runner"]

[tool.hatch.build.targets.sdist]
only-include = ["src"]

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
use_parentheses = true

[tool.mypy]
check_untyped_defs = true
mypy_path = ["src"]
packages = ["virby_vm_runner"]
pretty = true
python_version = "3.13"
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ruff]
fix = true
line-length = 100

[tool.uv]
package = true
default-groups = ["dev"]
